### ISSUE TITLE
Altering the indicator radius does not update the active indicator size

### ISSUE THREAD

**Issue by joeljfischer** [popwarsweet/PageControls#11]
I am only using the `SnakePageControl`. I believe it has to do with the `activeLayer` being `lazy` because the only way for me to make the active indicator not be 5 points is to manually change the file's `indicatorRadius` property within the `SnakePageControl.swift` file itself.

**Comment by popwarsweet** [comment]
@joeljfischer Thanks for bringing this up, it also exposed some other layout issues 👌.

**Comment by joeljfischer** [comment]
👍
