### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by JeremeLau** [popwarsweet/PageControls#13]
~/Pods/LLCycleScrollView/Lib/LLCycleScrollView/LLFilledPageControl.swift:119:34: Type 'CAShapeLayerFillRule' (aka 'NSString') has no member 'evenOdd'

somebody help 
With Xcode Version 10.1 (10B61)
With Swift 4.2

**Comment by kolorobos** [comment]
It was renamed. Just change the line to `layer.fillRule = CAShapeLayerFillRule.evenOdd`.
