### ISSUE TITLE
Compiler errors in Xcode 8 Beta 6

### ISSUE THREAD

**Issue by xoniq** [popwarsweet/PageControls#3]
I got this error:

`../Pods/PageControls/PageControls/Classes/SnakePageControl.swift:118:24: Method does not override any method from its superclass`

If I remove the `override` this is the result:

`.../Pods/PageControls/PageControls/Classes/FilledPageControl.swift:118:24: Method 'intrinsicContentSize()' with Objective-C selector 'intrinsicContentSize' conflicts with getter for 'intrinsicContentSize' from superclass 'UIView' with the same Objective-C selector`

This happens four times in the same file.

**Comment by popwarsweet** [comment]
There is now a feature/swift3 branch which will work on the beta version of Xcode.
