### ISSUE TITLE
Center page control in its frame

### ISSUE THREAD

**Issue by amarcadet** [popwarsweet/PageControls#4]
I'm facing an issue with the `FilledPageControl` where the items are not centered horizontally in the frame of the page control.

IB displays an error if I don't set a width or x constraint so the page control can't center itself in its superview. If I apply a center horizontally constraint it doesn't fix the error either.

**Comment by popwarsweet** [comment]
@amarcadet  Each page control has a calculated intrinsicContentSize and therefore doesn't need width or height constraints, setting a top constraint and horizontally centered constraint will do the trick. If for some reason you are unable to get IB to cooperate, you can set a placeholder size w/in IB and the intrinsicContentSize will be respected at runtime.

**Comment by amarcadet** [comment]
Nice catch on the placeholder size, because it looks like the `intrinsicContentSize` is not working.
