### ISSUE TITLE
IBDesignable not rendering in IB

### ISSUE THREAD

**Issue by amarcadet** [popwarsweet/PageControls#5]
I might be missing something, or it could be my Xcode having some issues but there is no rendering in IB.

I'm using Xcode 7.3.1 (7D1014).

**Comment by popwarsweet** [comment]
Have you set Page Count > 0 in IB?

**Comment by popwarsweet** [comment]
@amarcadet

**Comment by amarcadet** [comment]
Yep I have set all the IBInspectable properties to be sure, even `progress`.

**Comment by popwarsweet** [comment]
@amarcadet  Have you set the Module name to PageControls? This may be the cause to both of your issues.

**Comment by amarcadet** [comment]
Yes done it, could this be related to cocoapods ?

**Comment by amarcadet** [comment]
I've copy/pasted the code inside my project and now the page control is correctly rendering in IB, might definitely be related to cocoapods.

**Comment by amarcadet** [comment]
Well now the `intrinsicContentSize` is working too...

**Comment by amarcadet** [comment]
Gone back to cocoapods and it's working now... Really sorry for bringing these issues to you.
Xcode was doing his job fine as always ¯_(ツ)_/¯

**Comment by popwarsweet** [comment]
@amarcadet Thanks for bringing it up. I should add it to the README. Glad Xcode started working again :P
