### ISSUE TITLE
Changelog and Swift version

### ISSUE THREAD

**Issue by amarcadet** [popwarsweet/PageControls#7]
Hi,

Could you put a Changelog in the project or/and add information with tags/release ?

Could you also put Swift version requirements? 
It seems like from 0.x to 1.x we moved from Swift 2.x to 3.x.

Thanks for your work!

**Comment by popwarsweet** [comment]
Ajouté: https://github.com/popwarsweet/PageControls/blob/master/CHANGELOG.md
